// src/ui/combate/test/listadoTest.js

const test = {
  // TIER 1: CONCEPTOS BÁSICOS DE LÓGICA (RAZONAMIENTO / FUNDAMENTOS)
  tier1: [
    {
      id: "T1-001",
      tier: 1,
      pregunta: "Si A = verdadero y B = falso, ¿cuál es el resultado de (A AND B)?",
      opciones: ["Verdadero", "Falso", "Depende", "No se puede saber"],
      respuesta: 1,
      feedbackOk: "Correcto: verdadero AND falso = falso.",
      feedbackFail: "Corrección: AND solo es verdadero si ambos son verdaderos.",
    },
    {
      id: "T1-002",
      tier: 1,
      pregunta: "Si A = verdadero y B = falso, ¿cuál es el resultado de (A OR B)?",
      opciones: ["Verdadero", "Falso", "Depende", "No se puede saber"],
      respuesta: 0,
      feedbackOk: "Correcto: verdadero OR falso = verdadero.",
      feedbackFail: "Corrección: OR es verdadero si al menos uno es verdadero.",
    },
    {
      id: "T1-003",
      tier: 1,
      pregunta: "¿Cuál es la negación (NOT) de verdadero?",
      opciones: ["Verdadero", "Falso", "1", "0"],
      respuesta: 1,
      feedbackOk: "Correcto: NOT verdadero = falso.",
      feedbackFail: "Corrección: el operador NOT invierte el valor lógico.",
    },
    {
      id: "T1-004",
      tier: 1,
      pregunta: "Si un número es par, entonces es divisible por 2. ¿Cuál de estos números cumple la condición?",
      opciones: ["9", "11", "14", "17"],
      respuesta: 2,
      feedbackOk: "Correcto: 14 es par y divisible por 2.",
      feedbackFail: "Corrección: los pares terminan en 0,2,4,6,8; 14 cumple.",
    },
    {
      id: "T1-005",
      tier: 1,
      pregunta: "Completa la secuencia: 2, 4, 6, 8, __",
      opciones: ["9", "10", "11", "12"],
      respuesta: 1,
      feedbackOk: "Correcto: es una secuencia de +2, sigue 10.",
      feedbackFail: "Corrección: se suma 2 en cada paso, por eso sigue 10.",
    },
    {
      id: "T1-006",
      tier: 1,
      pregunta: "Si X > 5 y X < 10, ¿cuál valor es válido?",
      opciones: ["5", "7", "10", "12"],
      respuesta: 1,
      feedbackOk: "Correcto: 7 está entre 5 y 10.",
      feedbackFail: "Corrección: debe ser mayor que 5 y menor que 10; 7 cumple.",
    },
    {
      id: "T1-007",
      tier: 1,
      pregunta: "Un algoritmo es:",
      opciones: [
        "Una imagen en la pantalla",
        "Un conjunto de pasos para resolver un problema",
        "Un tipo de computadora",
        "Un archivo de música",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: un algoritmo es una secuencia de pasos.",
      feedbackFail: "Corrección: algoritmo = pasos ordenados para lograr un objetivo.",
    },
    {
      id: "T1-008",
      tier: 1,
      pregunta: "¿Qué estructura representa 'si pasa esto, entonces hago esto'?",
      opciones: ["Secuencia", "Condición (if)", "Entrada/Salida", "Comentario"],
      respuesta: 1,
      feedbackOk: "Correcto: eso es una condición (if).",
      feedbackFail: "Corrección: una condición evalúa una expresión y decide qué camino tomar.",
    },
    {
      id: "T1-009",
      tier: 1,
      pregunta: "¿Qué estructura se usa para repetir una acción varias veces?",
      opciones: ["Bucle (loop)", "Variable", "Constante", "Operador NOT"],
      respuesta: 0,
      feedbackOk: "Correcto: los bucles repiten instrucciones.",
      feedbackFail: "Corrección: un bucle permite repetición controlada (for/while).",
    },
    {
      id: "T1-010",
      tier: 1,
      pregunta: "Si hoy es martes, ¿qué día será dentro de 2 días?",
      opciones: ["Miércoles", "Jueves", "Viernes", "Sábado"],
      respuesta: 1,
      feedbackOk: "Correcto: martes + 2 días = jueves.",
      feedbackFail: "Corrección: miércoles (1), jueves (2).",
    },
    {
      id: "T1-011",
      tier: 1,
      pregunta: "¿Qué operador compara si dos valores son iguales?",
      opciones: ["Suma (+)", "Asignación (=)", "Igualdad (==)", "Negación (!)"],
      respuesta: 2,
      feedbackOk: "Correcto: el operador de igualdad compara (==).",
      feedbackFail: "Corrección: (==) compara; (=) suele asignar.",
    },
    {
      id: "T1-012",
      tier: 1,
      pregunta: "Si en una lista hay 5 elementos, ¿cuál es el índice del primer elemento en sistemas con indexación desde 0?",
      opciones: ["0", "1", "4", "5"],
      respuesta: 0,
      feedbackOk: "Correcto: el primer índice es 0.",
      feedbackFail: "Corrección: en indexación desde 0, el primero es 0.",
    },
    {
      id: "T1-013",
      tier: 1,
      pregunta: "¿Cuál de estas es una entrada (input) típica de un programa?",
      opciones: ["Teclado", "Pantalla", "Altavoz", "Impresora"],
      respuesta: 0,
      feedbackOk: "Correcto: el teclado es un dispositivo de entrada.",
      feedbackFail: "Corrección: pantalla/altavoz/impresora son salidas; teclado es entrada.",
    },
    {
      id: "T1-014",
      tier: 1,
      pregunta: "En un diagrama de flujo, ¿qué figura suele representar una decisión?",
      opciones: ["Rectángulo", "Rombo", "Círculo", "Triángulo"],
      respuesta: 1,
      feedbackOk: "Correcto: el rombo representa una decisión.",
      feedbackFail: "Corrección: el rombo indica una condición con salidas Sí/No.",
    },
    {
      id: "T1-015",
      tier: 1,
      pregunta: "Si un número termina en 0,2,4,6 u 8, entonces es:",
      opciones: ["Primo", "Impar", "Par", "Negativo"],
      respuesta: 2,
      feedbackOk: "Correcto: termina en dígito par, entonces es par.",
      feedbackFail: "Corrección: esos dígitos indican números pares.",
    },
    {
      id: "T1-016",
      tier: 1,
      pregunta: "¿Qué significa 'depurar' (debug) en programación?",
      opciones: [
        "Borrar el proyecto",
        "Encontrar y corregir errores",
        "Cambiar el color de la interfaz",
        "Comprimir archivos",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: depurar es encontrar y corregir errores.",
      feedbackFail: "Corrección: debug = analizar fallos y arreglarlos.",
    },
    {
      id: "T1-017",
      tier: 1,
      pregunta: "Si una condición es falsa, un bloque if normalmente:",
      opciones: [
        "Se ejecuta igual",
        "No se ejecuta",
        "Se ejecuta dos veces",
        "Borra variables",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: si es falsa, no se ejecuta el bloque if.",
      feedbackFail: "Corrección: el if solo corre cuando la condición es verdadera.",
    },
    {
      id: "T1-018",
      tier: 1,
      pregunta: "Completa la secuencia: 1, 1, 2, 3, 5, __",
      opciones: ["6", "7", "8", "9"],
      respuesta: 2,
      feedbackOk: "Correcto: es Fibonacci; 3 + 5 = 8.",
      feedbackFail: "Corrección: cada término es la suma de los dos anteriores; sigue 8.",
    },
    {
      id: "T1-019",
      tier: 1,
      pregunta: "¿Cuál es la salida de: si (10 > 3) entonces 'OK'?",
      opciones: ["OK", "FAIL", "Nada", "Error"],
      respuesta: 0,
      feedbackOk: "Correcto: 10 > 3 es verdadero, imprime OK.",
      feedbackFail: "Corrección: como la condición es verdadera, la salida es OK.",
    },
    {
      id: "T1-020",
      tier: 1,
      pregunta: "¿Qué concepto describe 'guardar un valor con un nombre'?",
      opciones: ["Variable", "Bucle", "Condición", "Compilador"],
      respuesta: 0,
      feedbackOk: "Correcto: una variable almacena un valor con un nombre.",
      feedbackFail: "Corrección: variable = nombre + valor (almacenamiento).",
    },
  ],

  // TIER 2: CONCEPTOS BÁSICOS ENFOCADOS A C++ (FUNDAMENTOS DEL LENGUAJE)
  tier2: [
    {
      id: "T2-001",
      tier: 2,
      pregunta: "¿Cuál es el punto de entrada típico de un programa en C++?",
      opciones: ["start()", "main()", "begin()", "entry()"],
      respuesta: 1,
      feedbackOk: "Correcto: main() es el punto de entrada.",
      feedbackFail: "Corrección: en C++ normalmente el programa inicia en main().",
    },
    {
      id: "T2-002",
      tier: 2,
      pregunta: "¿Qué librería se usa comúnmente para imprimir en consola (cout)?",
      opciones: ["<math.h>", "<iostream>", "<vector>", "<string>"],
      respuesta: 1,
      feedbackOk: "Correcto: cout está en <iostream>.",
      feedbackFail: "Corrección: incluye <iostream> para usar std::cout.",
    },
    {
      id: "T2-003",
      tier: 2,
      pregunta: "¿Qué palabra clave se usa para definir una constante en C++?",
      opciones: ["final", "const", "static", "let"],
      respuesta: 1,
      feedbackOk: "Correcto: const define valores no modificables.",
      feedbackFail: "Corrección: const evita cambios accidentales del valor.",
    },
    {
      id: "T2-004",
      tier: 2,
      pregunta: "¿Qué tipo de dato es apropiado para guardar un número entero?",
      opciones: ["int", "float", "char", "bool"],
      respuesta: 0,
      feedbackOk: "Correcto: int se usa para enteros.",
      feedbackFail: "Corrección: int representa números enteros.",
    },
    {
      id: "T2-005",
      tier: 2,
      pregunta: "¿Qué tipo de dato se usa para verdadero/falso?",
      opciones: ["bool", "char", "double", "string"],
      respuesta: 0,
      feedbackOk: "Correcto: bool representa valores lógicos.",
      feedbackFail: "Corrección: bool solo puede ser true o false.",
    },
    {
      id: "T2-006",
      tier: 2,
      pregunta: "¿Qué símbolo se usa para terminar una instrucción en C++?",
      opciones: [":", ".", ";", ","],
      respuesta: 2,
      feedbackOk: "Correcto: el punto y coma (;) finaliza la instrucción.",
      feedbackFail: "Corrección: en C++ la mayoría de sentencias terminan con ';'.",
    },
    {
      id: "T2-007",
      tier: 2,
      pregunta: "¿Qué es un 'namespace' en C++?",
      opciones: [
        "Un archivo ejecutable",
        "Un espacio de nombres para organizar identificadores",
        "Un tipo de variable",
        "Un bucle especial",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: namespace organiza nombres (ej: std).",
      feedbackFail: "Corrección: namespace evita choques de nombres y organiza el código.",
    },
    {
      id: "T2-008",
      tier: 2,
      pregunta: "¿Cuál de estas líneas imprime texto en consola?",
      opciones: [
        "print('Hola');",
        "System.out.println('Hola');",
        "std::cout << \"Hola\";",
        "console.log('Hola');",
      ],
      respuesta: 2,
      feedbackOk: "Correcto: std::cout es salida estándar en C++.",
      feedbackFail: "Corrección: en C++ se usa std::cout << \"texto\";",
    },
    {
      id: "T2-009",
      tier: 2,
      pregunta: "¿Cuál operador se usa para sumar en C++?",
      opciones: ["+", "*", "=", "!="],
      respuesta: 0,
      feedbackOk: "Correcto: + suma valores.",
      feedbackFail: "Corrección: + es el operador de suma.",
    },
    {
      id: "T2-010",
      tier: 2,
      pregunta: "¿Qué estructura se usa para repetir con un contador típico?",
      opciones: ["for", "switch", "class", "typedef"],
      respuesta: 0,
      feedbackOk: "Correcto: for es común para iteraciones contadas.",
      feedbackFail: "Corrección: for sirve para repetir con inicio/condición/avance.",
    },
    {
      id: "T2-011",
      tier: 2,
      pregunta: "¿Qué estructura se usa para tomar decisiones en C++?",
      opciones: ["if", "include", "using", "return"],
      respuesta: 0,
      feedbackOk: "Correcto: if evalúa condiciones.",
      feedbackFail: "Corrección: if ejecuta un bloque según una condición.",
    },
    {
      id: "T2-012",
      tier: 2,
      pregunta: "¿Qué hace 'return 0;' típicamente en main()?",
      opciones: [
        "Indica que hubo un error",
        "Indica salida exitosa",
        "Reinicia el programa",
        "Imprime 0 en consola",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: 0 suele indicar éxito.",
      feedbackFail: "Corrección: por convención, return 0 indica ejecución correcta.",
    },
    {
      id: "T2-013",
      tier: 2,
      pregunta: "¿Qué es una función en C++?",
      opciones: [
        "Un tipo de variable",
        "Un bloque reutilizable que puede recibir parámetros y devolver un resultado",
        "Una clase sin atributos",
        "Un comentario",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: las funciones encapsulan lógica reutilizable.",
      feedbackFail: "Corrección: función = bloque de código reutilizable (con parámetros/retorno).",
    },
    {
      id: "T2-014",
      tier: 2,
      pregunta: "¿Qué es un 'vector' (std::vector) en C++?",
      opciones: [
        "Una función para imprimir",
        "Un arreglo dinámico (contenedor) de la STL",
        "Un tipo de puntero",
        "Una librería de red",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: std::vector es un contenedor dinámico.",
      feedbackFail: "Corrección: vector almacena elementos y puede crecer automáticamente.",
    },
    {
      id: "T2-015",
      tier: 2,
      pregunta: "¿Cómo se accede típicamente al tamaño de un std::vector v?",
      opciones: ["v.length()", "v.size()", "size(v)", "v.count()"],
      respuesta: 1,
      feedbackOk: "Correcto: v.size() devuelve el tamaño.",
      feedbackFail: "Corrección: en STL, los contenedores suelen exponer size().",
    },
    {
      id: "T2-016",
      tier: 2,
      pregunta: "¿Qué palabra clave se usa para crear una clase en C++?",
      opciones: ["struct", "class", "object", "module"],
      respuesta: 1,
      feedbackOk: "Correcto: class define una clase.",
      feedbackFail: "Corrección: en C++ se usa class (o struct) para definir tipos.",
    },
    {
      id: "T2-017",
      tier: 2,
      pregunta: "¿Qué significa 'compilar' un programa C++?",
      opciones: [
        "Ejecutarlo directamente sin pasos",
        "Traducir el código fuente a un ejecutable/código máquina",
        "Subirlo a internet",
        "Convertirlo a JavaScript",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: compilar = traducir a un ejecutable.",
      feedbackFail: "Corrección: el compilador convierte el código C++ en código ejecutable.",
    },
    {
      id: "T2-018",
      tier: 2,
      pregunta: "¿Qué es un 'header' (.h / .hpp) en C++?",
      opciones: [
        "Un archivo solo para imágenes",
        "Un archivo que suele contener declaraciones (interfaces) e includes",
        "Un archivo ejecutable",
        "Un archivo de audio",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: en headers se declaran funciones/clases y se incluyen dependencias.",
      feedbackFail: "Corrección: header = declaraciones y contratos; implementación suele ir en .cpp.",
    },
    {
      id: "T2-019",
      tier: 2,
      pregunta: "¿Qué operador se usa para comparar igualdad en C++?",
      opciones: ["=", "==", "===", "=>"],
      respuesta: 1,
      feedbackOk: "Correcto: == compara igualdad.",
      feedbackFail: "Corrección: = asigna; == compara.",
    },
    {
      id: "T2-020",
      tier: 2,
      pregunta: "¿Qué imprime este código? int x = 3; x += 2;",
      opciones: ["x vale 1", "x vale 2", "x vale 5", "x vale 6"],
      respuesta: 2,
      feedbackOk: "Correcto: x pasa de 3 a 5 con += 2.",
      feedbackFail: "Corrección: x += 2 equivale a x = x + 2; entonces x = 5.",
    },
  ],

  // TIER 3: CONCEPTOS TÉCNICOS DE C++ (MÁS PROFUNDO)
  tier3: [
    {
      id: "T3-001",
      tier: 3,
      pregunta: "En C++, ¿qué significa RAII?",
      opciones: [
        "Run All Instructions Instantly",
        "Resource Acquisition Is Initialization",
        "Random Access Inheritance Interface",
        "Runtime Allocation Is Illegal",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: RAII liga recursos al ciclo de vida de objetos (constructor/destructor).",
      feedbackFail: "Corrección: RAII = gestionar recursos automáticamente con constructores/destructores.",
    },
    {
      id: "T3-002",
      tier: 3,
      pregunta: "¿Qué hace 'delete[]' en C++?",
      opciones: [
        "Libera memoria asignada con new para un solo objeto",
        "Libera memoria asignada con new[] para arreglos",
        "Resetea un puntero a nullptr",
        "Destruye un stack frame",
      ],
      respuesta: 1,
      feedbackOk: "Bien: delete[] se usa para memoria reservada con new[].",
      feedbackFail: "Corrección: delete[] libera arreglos creados con new[]; delete es para uno solo.",
    },
    {
      id: "T3-003",
      tier: 3,
      pregunta: "¿Qué es un 'dangling pointer'?",
      opciones: [
        "Un puntero a memoria ya liberada o inválida",
        "Un puntero constante",
        "Un puntero nulo",
        "Un puntero a una función",
      ],
      respuesta: 0,
      feedbackOk: "Correcto: apunta a memoria inválida (ya liberada o fuera de scope).",
      feedbackFail: "Corrección: dangling pointer queda apuntando a memoria que ya no es válida.",
    },
    {
      id: "T3-004",
      tier: 3,
      pregunta: "¿Qué ventaja principal aporta std::unique_ptr?",
      opciones: [
        "Copia automática del recurso",
        "Propiedad exclusiva y liberación automática (RAII)",
        "Permite múltiples dueños del mismo recurso",
        "Evita el uso de destructores",
      ],
      respuesta: 1,
      feedbackOk: "Bien: unique_ptr expresa propiedad exclusiva y libera automáticamente.",
      feedbackFail: "Corrección: unique_ptr implementa RAII; no se copia, se mueve.",
    },
    {
      id: "T3-005",
      tier: 3,
      pregunta: "¿Qué contenedor de STL es típicamente O(1) para push_back amortizado?",
      opciones: ["std::list", "std::vector", "std::map", "std::set"],
      respuesta: 1,
      feedbackOk: "Correcto: std::vector tiene push_back amortizado O(1).",
      feedbackFail: "Corrección: vector crece por capacidad; por eso push_back es amortizado O(1).",
    },
    {
      id: "T3-006",
      tier: 3,
      pregunta: "¿Qué significa 'move semantics' en C++?",
      opciones: [
        "Mover variables entre hilos",
        "Transferir recursos sin copiar (usando rvalue references)",
        "Convertir int a float",
        "Optimizar bucles for",
      ],
      respuesta: 1,
      feedbackOk: "Bien: mover transfiere recursos sin copiar (más eficiente).",
      feedbackFail: "Corrección: move semantics usa rvalue references para transferir recursos sin copias.",
    },
    {
      id: "T3-007",
      tier: 3,
      pregunta: "¿Qué es 'const correctness'?",
      opciones: [
        "Usar const para permitir cambios seguros",
        "Diseñar APIs donde const evita modificaciones no deseadas",
        "Eliminar la palabra const para rendimiento",
        "Usar const solo en macros",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: const ayuda a garantizar qué se puede modificar y qué no.",
      feedbackFail: "Corrección: const correctness diseña el código para no modificar datos cuando no corresponde.",
    },
    {
      id: "T3-008",
      tier: 3,
      pregunta: "¿Cuál es la diferencia entre referencia y puntero en C++?",
      opciones: [
        "No hay diferencia",
        "Una referencia no puede ser null y se vincula al inicializar; un puntero sí puede ser null",
        "Un puntero siempre es más rápido",
        "Una referencia se puede reasignar, un puntero no",
      ],
      respuesta: 1,
      feedbackOk: "Bien: referencias se enlazan una vez; punteros pueden ser null y reasignarse.",
      feedbackFail: "Corrección: referencia no suele ser null y se inicializa al declarar; puntero puede ser null.",
    },
    {
      id: "T3-009",
      tier: 3,
      pregunta: "¿Qué hace 'virtual' en un método de C++?",
      opciones: [
        "Hace el método privado",
        "Permite despacho dinámico (polimorfismo en runtime)",
        "Evita el uso de punteros",
        "Convierte la clase en template",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: virtual habilita polimorfismo con llamadas dinámicas.",
      feedbackFail: "Corrección: virtual permite resolver la llamada en runtime según el tipo real.",
    },
    {
      id: "T3-010",
      tier: 3,
      pregunta: "¿Qué es una 'vtable'?",
      opciones: [
        "Una tabla de hashes estándar",
        "Estructura usada para resolver llamadas virtuales en runtime",
        "Un vector de enteros",
        "Un archivo de compilación",
      ],
      respuesta: 1,
      feedbackOk: "Bien: la vtable ayuda a resolver métodos virtuales en runtime.",
      feedbackFail: "Corrección: vtable soporta el despacho dinámico de funciones virtuales.",
    },
    {
      id: "T3-011",
      tier: 3,
      pregunta: "¿Qué ocurre si una clase tiene un destructor virtual?",
      opciones: [
        "No puede heredarse",
        "Asegura destrucción correcta al borrar vía puntero base",
        "Impide el uso de new",
        "Hace la clase abstracta automáticamente",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: garantiza destrucción correcta al hacer delete mediante puntero base.",
      feedbackFail: "Corrección: sin destructor virtual, delete vía base puede no llamar el destructor derivado.",
    },
    {
      id: "T3-012",
      tier: 3,
      pregunta: "¿Qué es SFINAE en C++?",
      opciones: [
        "Un tipo de puntero inteligente",
        "Una regla: Substitution Failure Is Not An Error (en templates)",
        "Un modo de compilación",
        "Una librería de IO",
      ],
      respuesta: 1,
      feedbackOk: "Bien: SFINAE permite habilitar/deshabilitar templates según tipos válidos.",
      feedbackFail: "Corrección: SFINAE evita error duro cuando la sustitución de tipos no aplica en templates.",
    },
    {
      id: "T3-013",
      tier: 3,
      pregunta: "¿Qué contenedor mantiene claves ordenadas automáticamente?",
      opciones: ["std::unordered_map", "std::vector", "std::map", "std::queue"],
      respuesta: 2,
      feedbackOk: "Correcto: std::map mantiene orden (árbol balanceado).",
      feedbackFail: "Corrección: map mantiene claves ordenadas; unordered_map no garantiza orden.",
    },
    {
      id: "T3-014",
      tier: 3,
      pregunta: "¿Qué significa 'undefined behavior' (UB) en C++?",
      opciones: [
        "El programa siempre crashea",
        "El estándar no define el resultado; puede pasar cualquier cosa",
        "El compilador lo corrige automáticamente",
        "Solo afecta a Windows",
      ],
      respuesta: 1,
      feedbackOk: "Bien: UB significa que no hay resultado garantizado por el estándar.",
      feedbackFail: "Corrección: undefined behavior es comportamiento no definido; puede variar según compilador/optimización.",
    },
    {
      id: "T3-015",
      tier: 3,
      pregunta: "¿Cuál es el propósito de std::move?",
      opciones: [
        "Mover datos físicamente en memoria",
        "Convertir a rvalue para habilitar movimientos",
        "Copiar más rápido",
        "Eliminar un objeto del heap",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: std::move convierte a rvalue para permitir mover.",
      feedbackFail: "Corrección: std::move no mueve por sí solo; habilita move semantics.",
    },
    {
      id: "T3-016",
      tier: 3,
      pregunta: "¿Qué es la 'Rule of Five'?",
      opciones: [
        "Cinco tipos de loops",
        "Constructor, destructor, copy/move ctor y copy/move assign",
        "Cinco palabras reservadas",
        "Cinco contenedores de STL",
      ],
      respuesta: 1,
      feedbackOk: "Bien: si manejas recursos, considera definir esos 5 miembros especiales.",
      feedbackFail: "Corrección: Rule of Five = dtor + copy/move ctor + copy/move assignment.",
    },
    {
      id: "T3-017",
      tier: 3,
      pregunta: "¿Qué es un 'lambda' en C++?",
      opciones: [
        "Una clase abstracta",
        "Una función anónima (objeto callable)",
        "Un tipo de puntero",
        "Un macro del preprocesador",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: lambda es una función anónima con captura opcional.",
      feedbackFail: "Corrección: lambda crea un callable (función anónima) que puede capturar variables.",
    },
    {
      id: "T3-018",
      tier: 3,
      pregunta: "¿Qué complejidad tiene buscar una clave en std::unordered_map (promedio)?",
      opciones: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
      respuesta: 0,
      feedbackOk: "Bien: en promedio es O(1) si el hash está bien distribuido.",
      feedbackFail: "Corrección: unordered_map es promedio O(1), pero puede degradar con muchas colisiones.",
    },
    {
      id: "T3-019",
      tier: 3,
      pregunta: "¿Qué es 'template specialization'?",
      opciones: [
        "Herencia múltiple",
        "Definir una implementación específica de un template para ciertos tipos",
        "Optimizar el compilador",
        "Eliminar warnings",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: specialization adapta un template para tipos concretos.",
      feedbackFail: "Corrección: specialization permite una versión específica del template para ciertos tipos.",
    },
    {
      id: "T3-020",
      tier: 3,
      pregunta: "¿Qué hace 'constexpr' en C++ (idea principal)?",
      opciones: [
        "Ejecuta código en la GPU",
        "Permite evaluación en tiempo de compilación cuando es posible",
        "Desactiva optimizaciones",
        "Convierte a const automáticamente",
      ],
      respuesta: 1,
      feedbackOk: "Bien: constexpr habilita cálculos en compile-time cuando aplica.",
      feedbackFail: "Corrección: constexpr permite que el compilador evalúe expresiones en tiempo de compilación si puede.",
    },
  ],

  // TIER 4: CONCEPTOS TÉCNICOS APLICADOS A UNITY (MÁS PROFUNDO / PRÁCTICO)
  tier4: [
    {
      id: "T4-001",
      tier: 4,
      pregunta: "¿Qué método se recomienda para aplicar fuerzas a un Rigidbody de forma consistente con la física?",
      opciones: ["Update()", "FixedUpdate()", "LateUpdate()", "OnGUI()"],
      respuesta: 1,
      feedbackOk: "Correcto: FixedUpdate() se alinea con el paso fijo de física.",
      feedbackFail: "Corrección: fuerzas/movimiento con Rigidbody se recomienda en FixedUpdate().",
    },
    {
      id: "T4-002",
      tier: 4,
      pregunta: "¿Qué modo de Rigidbody se usa para moverlo con física pero controlando la posición vía código correctamente?",
      opciones: ["Transform.Translate()", "Rigidbody.MovePosition()", "Renderer.Move()", "Collider.Move()"],
      respuesta: 1,
      feedbackOk: "Correcto: MovePosition() es apropiado para movimiento cinemático controlado.",
      feedbackFail: "Corrección: Rigidbody.MovePosition() evita problemas típicos de mover por Transform en física.",
    },
    {
      id: "T4-003",
      tier: 4,
      pregunta: "¿Qué configuración evita que un Rigidbody rote por colisiones (sin congelar posición)?",
      opciones: ["Use Gravity", "Interpolate", "Constraints: Freeze Rotation", "Is Kinematic"],
      respuesta: 2,
      feedbackOk: "Correcto: Freeze Rotation bloquea la rotación.",
      feedbackFail: "Corrección: en Constraints puedes congelar rotaciones específicas o todas.",
    },
    {
      id: "T4-004",
      tier: 4,
      pregunta: "¿Qué diferencia práctica hay entre Update() y FixedUpdate()?",
      opciones: [
        "Update corre con física, FixedUpdate con UI",
        "Update es por frame, FixedUpdate es por paso fijo de física",
        "Update solo corre una vez, FixedUpdate siempre",
        "No hay diferencia",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: Update es por frame; FixedUpdate es para física con timestep fijo.",
      feedbackFail: "Corrección: física en FixedUpdate; lógica general/inputs en Update (según el caso).",
    },
    {
      id: "T4-005",
      tier: 4,
      pregunta: "Para detectar clics/taps sobre objetos 3D, normalmente se usa:",
      opciones: ["Raycast desde cámara", "Collider sin cámara", "AudioSource", "NavMeshAgent"],
      respuesta: 0,
      feedbackOk: "Correcto: se lanza un Raycast desde la cámara hacia la escena.",
      feedbackFail: "Corrección: Raycast + Collider permite detectar qué objeto fue seleccionado.",
    },
    {
      id: "T4-006",
      tier: 4,
      pregunta: "¿Qué es un ScriptableObject y por qué es útil en Unity?",
      opciones: [
        "Un componente de UI",
        "Un asset de datos reutilizable, ideal para configuración fuera de escenas",
        "Un tipo de shader",
        "Un sistema de partículas",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: permite guardar data/config como assets reutilizables.",
      feedbackFail: "Corrección: ScriptableObject separa datos de escenas y facilita reuse/edición.",
    },
    {
      id: "T4-007",
      tier: 4,
      pregunta: "¿Qué componente debe existir para UI tradicional (UGUI) y que se vea en pantalla?",
      opciones: ["Canvas", "Rigidbody", "Light", "MeshFilter"],
      respuesta: 0,
      feedbackOk: "Correcto: la UI UGUI vive dentro de un Canvas.",
      feedbackFail: "Corrección: sin Canvas, los elementos UI no se renderizan como UI.",
    },
    {
      id: "T4-008",
      tier: 4,
      pregunta: "En Unity, ¿qué técnica se recomienda para no llamar GetComponent repetidamente en Update?",
      opciones: ["Llamarlo 60 veces por segundo", "Cachear la referencia en Awake/Start", "Usar Debug.Log", "Cambiar la escena"],
      respuesta: 1,
      feedbackOk: "Correcto: cachear referencias mejora rendimiento y claridad.",
      feedbackFail: "Corrección: guarda el componente en una variable en Awake/Start y reutilízalo.",
    },
    {
      id: "T4-009",
      tier: 4,
      pregunta: "¿Qué diferencia hay entre Instantiate(prefab) y usar un GameObject ya en escena?",
      opciones: [
        "Instantiate crea una instancia nueva; el de escena ya existe",
        "No hay diferencia",
        "Instantiate solo funciona con UI",
        "Instantiate elimina el original",
      ],
      respuesta: 0,
      feedbackOk: "Correcto: Instantiate clona un prefab/objeto y crea uno nuevo.",
      feedbackFail: "Corrección: Instantiate crea instancias; el objeto en escena ya está creado.",
    },
    {
      id: "T4-010",
      tier: 4,
      pregunta: "¿Qué ocurre al desactivar un GameObject con SetActive(false)?",
      opciones: [
        "Se destruye para siempre",
        "Se pausa: no se renderiza ni ejecuta scripts mientras esté inactivo",
        "Se convierte en Prefab",
        "Se guarda automáticamente en Project",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: inactivo = no render y no ejecución.",
      feedbackFail: "Corrección: no se destruye; solo deja de funcionar hasta reactivarlo.",
    },
    {
      id: "T4-011",
      tier: 4,
      pregunta: "Para transiciones suaves de cámara, una técnica común es:",
      opciones: ["Mover con saltos", "Interpolar con Lerp/SmoothDamp", "Reiniciar la escena", "Desactivar la cámara"],
      respuesta: 1,
      feedbackOk: "Correcto: Lerp/SmoothDamp permite transiciones suaves.",
      feedbackFail: "Corrección: la interpolación evita movimientos bruscos.",
    },
    {
      id: "T4-012",
      tier: 4,
      pregunta: "¿Qué sistema se usa para pathfinding en Unity (navegación de agentes)?",
      opciones: ["NavMesh", "SpriteAtlas", "Profiler", "Animator Controller"],
      respuesta: 0,
      feedbackOk: "Correcto: NavMesh sirve para navegación y pathfinding.",
      feedbackFail: "Corrección: NavMesh + NavMeshAgent permiten rutas y evitación básica.",
    },
    {
      id: "T4-013",
      tier: 4,
      pregunta: "¿Qué hace Time.deltaTime típicamente en movimientos?",
      opciones: [
        "Hace el movimiento dependiente del FPS",
        "Hace el movimiento independiente del FPS (aprox.)",
        "Desactiva la gravedad",
        "Cambia el FOV",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: deltaTime ajusta por el tiempo real entre frames.",
      feedbackFail: "Corrección: multiplicar por deltaTime ayuda a mantener velocidad estable entre FPS distintos.",
    },
    {
      id: "T4-014",
      tier: 4,
      pregunta: "Para evitar que un Collider físico afecte objetos (pero detecte overlaps), se usa:",
      opciones: ["Is Trigger", "Is Static", "Interpolate", "Use Gravity"],
      respuesta: 0,
      feedbackOk: "Correcto: Is Trigger convierte colisión en evento de trigger.",
      feedbackFail: "Corrección: Trigger no empuja; dispara eventos OnTriggerEnter/Exit.",
    },
    {
      id: "T4-015",
      tier: 4,
      pregunta: "¿Qué diferencia clave hay entre OnCollisionEnter y OnTriggerEnter?",
      opciones: [
        "Collision funciona con triggers; Trigger con colliders sólidos",
        "OnCollisionEnter es para colisiones físicas; OnTriggerEnter es para triggers (sin empuje)",
        "Son exactamente lo mismo",
        "Solo funcionan en UI",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: Collision empuja/colisiona; Trigger detecta sin física de empuje.",
      feedbackFail: "Corrección: trigger detecta superposición; collision implica respuesta física.",
    },
    {
      id: "T4-016",
      tier: 4,
      pregunta: "¿Qué herramienta ayuda a medir rendimiento (CPU/GPU/frames) en Unity?",
      opciones: ["Profiler", "Hierarchy", "Scene View", "Package Manager"],
      respuesta: 0,
      feedbackOk: "Correcto: Profiler muestra métricas de rendimiento.",
      feedbackFail: "Corrección: Profiler es clave para detectar cuellos de botella.",
    },
    {
      id: "T4-017",
      tier: 4,
      pregunta: "¿Qué componente/asset se usa para controlar animaciones por estados y transiciones?",
      opciones: ["Animator Controller", "Audio Mixer", "Terrain Layer", "Lightmap"],
      respuesta: 0,
      feedbackOk: "Correcto: Animator Controller define estados, transiciones y parámetros.",
      feedbackFail: "Corrección: con Animator Controller controlas el flujo de animación.",
    },
    {
      id: "T4-018",
      tier: 4,
      pregunta: "Para persistir un objeto entre escenas (no destruirlo al cargar otra), se usa:",
      opciones: ["Destroy()", "DontDestroyOnLoad()", "Instantiate()", "SetActive(false)"],
      respuesta: 1,
      feedbackOk: "Correcto: DontDestroyOnLoad mantiene el objeto entre escenas.",
      feedbackFail: "Corrección: DontDestroyOnLoad evita que se destruya al cambiar de escena.",
    },
    {
      id: "T4-019",
      tier: 4,
      pregunta: "¿Cuál es una buena práctica para organizar eventos globales sin acoplar objetos directamente?",
      opciones: ["Hardcodear referencias en todos lados", "Usar eventos (C# events/UnityEvent) o un EventBus", "Duplicar scripts", "Usar solo Tags"],
      respuesta: 1,
      feedbackOk: "Correcto: eventos/eventbus reducen acoplamiento entre sistemas.",
      feedbackFail: "Corrección: un sistema de eventos permite comunicación sin referencias directas.",
    },
    {
      id: "T4-020",
      tier: 4,
      pregunta: "Si un input se lee en FixedUpdate, ¿qué problema común puede aparecer?",
      opciones: [
        "No se puede leer input en Unity",
        "El input puede perderse o sentirse inconsistente por el timestep fijo",
        "El input se vuelve más rápido",
        "Se desactiva la cámara",
      ],
      respuesta: 1,
      feedbackOk: "Correcto: el input se suele leer en Update y aplicar en FixedUpdate si es física.",
      feedbackFail: "Corrección: lectura de input en Update; aplicación física en FixedUpdate es el patrón común.",
    },
  ],
};

export default test;
